services:
  app:
    image: go-web-server-sample
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "1323:1323"
    volumes:
      - .:/app
    command: tail -f /dev/null
