FROM golang:1.21
WORKDIR /app
# for golang extension
RUN go install github.com/ramya-rao-a/go-outline@latest && \
  go install golang.org/x/tools/gopls@latest && \
  go install golang.org/x/tools/cmd/goimports@latest
